#!/usr/bin/env bash

# TODO (Run this script as): color magenta && echo hello && color reset

color() {
    echo -ne "\033[$1;$2m"
}

declare -A color_mapping=(
    # TODO: Add more color values
    # Refer bash color codes
    ['magenta']=35
     ['red']=31
    ['magenta']=35
    ['green']=32
    ['blue']=34
    ['cyan']=36 
    ['reset']=0
)

if [[ $1 == 'reset' ]]; then
    color 0 00
else
    color 1 ${color_mapping[$1]}
fi

