#!/usr/bin/env bash

# TODO: Make a ffmpeg script which takes all the mp4 files in a folder (recursively) and output them in the same position mp3 file
#
# E.g.:
# Videos
# ├── Clips
# │   ├── clip1.mp4
# │   └── clip2.mp4
# ├── Movies
# │   ├── movie1.mp4
# │   └── movie2.mp4
# └── Songs
#     ├── Song1.mp4
#     └── Song2.mp4
# music-extract Videos
#
# The above folder will create another folder with the position of file with just there audio
# Music
# ├── Clips
# │   ├── clip1.mp3
# │   └── clip2.mp3
# ├── Movies
# │   ├── movie1.mp3
# │   └── movie2.mp3
# └── Songs
#     ├── Song1.mp3
#     └── Song2.mp3
